# Automated Raydium CP-Swap Overflow Test
# This workflow is configured to run on a standard GitHub-hosted
# Ubuntu runner. It automates the setup, deployment, and testing
# of your Solana program.

name: Automated Raydium CP-Swap Overflow Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    # This job will run on a fresh Ubuntu virtual machine provided by GitHub.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Use the actions-rs/toolchain to install Rust, which is the
    # standard and most reliable method for Linux-based runners.
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Solana CLI and Dependencies
      run: |
        # Install necessary dependencies to ensure a successful `curl` and `git` operation.
        sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
        # Download and install the Solana CLI.
        sh -c "$(curl -sSfL https://release.solana.com/v1.18.2/install)"
        # Add the Solana bin directory to the PATH for subsequent steps.
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Install BPF Toolchain
      run: |
        # Add the Rust source component required for BPF development.
        rustup component add rust-src
        # Download and extract the BPF toolchain to a temporary directory
        # to avoid the `git clone` authentication error.
        mkdir -p /tmp/cargo-build-bpf
        curl -L https://github.com/solana-labs/cargo-build-bpf/archive/refs/tags/v1.18.2.tar.gz | tar -xzf - --strip-components=1 -C /tmp/cargo-build-bpf
        # Install the tool from the local path.
        cargo install --path /tmp/cargo-build-bpf

    - name: Start Solana Test Validator and Wait for Readiness
      run: |
        # Start the validator in the background. The --reset flag clears previous data.
        solana-test-validator --reset &
        
        # Poll the validator's health endpoint until it responds. This is more
        # reliable than a hard-coded sleep time.
        for i in `seq 1 10`; do
          solana ping > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Solana test validator is ready."
            exit 0
          fi
          echo "Waiting for validator... $i"
          sleep 5
        done
        
        echo "Solana test validator failed to start."
        exit 1

    - name: Build Raydium CP-Swap Program
      run: |
        # Build the Solana BPF program.
        cargo build-bpf --manifest-path=program/Cargo.toml

    - name: Deploy Program to Local Validator
      run: |
        # Find the compiled program file.
        PROGRAM_SO=$(find target/deploy -name '*.so' | head -n 1)
        # Deploy the program to the local validator and capture its Program ID.
        PROGRAM_ID=$(solana program deploy $PROGRAM_SO | grep 'Program Id:' | awk '{print $3}')
        # Export the Program ID as an environment variable for the next step.
        echo "PROGRAM_ID=$PROGRAM_ID" >> $GITHUB_ENV

    - name: Run Overflow Test
      env:
        # Pass the newly deployed Program ID to the test script.
        RAYDIUM_CP_SWAP_PROGRAM_ID: ${{ env.PROGRAM_ID }}
      run: |
        # Run your specified test.
        cargo test --test overflow_test
